# Generated by Django 2.2.17 on 2021-07-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0013_merge_20210107_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='approved',
            field=models.IntegerField(default=0),
        ),
    ]
