# Generated by Django 2.2.17 on 2021-07-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0014_answer_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='approved',
            field=models.IntegerField(choices=[(1, 'Approved'), (-1, 'Disapproved')], default=0),
        ),
    ]
