# Generated by Django 2.2.17 on 2021-07-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0017_team_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='team',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.Team'),
            preserve_default=False,
        ),
    ]
