# Generated by Django 2.2.17 on 2021-07-12 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0018_question_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.Team'),
        ),
    ]
