# Generated by Django 2.2.17 on 2021-07-14 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stackoverflow', '0023_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_by',
            field=models.ManyToManyField(related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
