# Generated by Django 2.2.17 on 2021-07-15 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0024_job_applied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_by',
            field=models.ManyToManyField(blank=True, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
