# Generated by Django 2.2.17 on 2021-07-15 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0025_auto_20210715_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 15, 5, 56, 41, 18278)),
            preserve_default=False,
        ),
    ]
