# Generated by Django 2.2.17 on 2021-07-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0026_job_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='indstry',
            field=models.CharField(default='software', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('question', models.ManyToManyField(related_name='technologies', to='stackoverflow.Job')),
            ],
        ),
    ]
