# Generated by Django 2.2.17 on 2021-07-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0027_auto_20210715_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologies',
            name='question',
        ),
        migrations.AddField(
            model_name='technologies',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='technologies', to='stackoverflow.Job'),
        ),
    ]
