# Generated by Django 2.2.17 on 2021-07-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0028_auto_20210715_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologies',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='technologies', to='stackoverflow.Technologies'),
        ),
    ]
